apiVersion: v2
name: applications
description: A Helm chart for microservices applications
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - microservices
  - fastapi
  - flask
  - jenkins
home: https://github.com/your-org/applications-chart
maintainers:
  - name: yogeshvk1209
    email: yogeshvk1209@gmail.com
