# Default values for cilium
image:
  repository: quay.io/cilium/cilium
  tag: v1.14.5
  pullPolicy: IfNotPresent

config:
  identityAllocationMode: crd
  endpointGcInterval: "5m0s"
  enableIPv4: true
  enableIPv6: false
  enableBpfClockProbe: true
  preallocateBpfMaps: false
  enableL7Proxy: true
  bpfPolicyMapMax: 16384
  enableBandwidthManager: false
  enableLocalRedirectPolicy: false

resources:
  limits:
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  capabilities:
    add:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID