{{- if .Values.fastapi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: {{ .Values.namespace.name }}
  labels:
    app: fastapi-app
spec:
  replicas: {{ .Values.fastapi.replicaCount }}
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi
        image: {{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag }}
        imagePullPolicy: {{ .Values.fastapi.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.fastapi.service.port }}
        resources:
          {{- toYaml .Values.fastapi.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.fastapi.service.type }}
  ports:
  - port: {{ .Values.fastapi.service.port }}
    targetPort: {{ .Values.fastapi.service.port }}
    protocol: TCP
  selector:
    app: fastapi-app
{{- end }}