{{- if .Values.flask.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: {{ .Values.namespace.name }}
  labels:
    app: flask-app
spec:
  replicas: {{ .Values.flask.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask
        image: {{ .Values.flask.image.repository }}:{{ .Values.flask.image.tag }}
        imagePullPolicy: {{ .Values.flask.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.flask.service.port }}
        resources:
          {{- toYaml .Values.flask.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.flask.service.type }}
  ports:
  - port: {{ .Values.flask.service.port }}
    targetPort: {{ .Values.flask.service.port }}
    protocol: TCP
  selector:
    app: flask-app
{{- end }}